# Site settings
title: 浮云计算
email: liriansu@gmail.com
description: "Lirian Su's Blog"
baseurl: ""
url: "http://www.cloudisdream.com"
weibo_username: lllki
github_username:  LKI

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!--MORE-->"

# Use Github Flavored Markdown
kramdown:
    input: GFM
