author:
  name: Lirian Su
baseURL: https://liriansu.com/
defaultContentLanguage: cn
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardWraps: true
languageCode: en-us
languages:
  cn:
    contentDir: content/cn
    languageName: 中文
    weight: 1
  en:
    contentDir: content/en
    languageName: English
    weight: 2
params:
  headTitle: Lirian Su
  socials:
    - name: about
      link: /about
    - name: github
      link: https://github.com/LKI
    - name: zhihu
      link: https://www.zhihu.com/people/liriansu
    - name: rss
      link: /index.xml
theme: yinyang
title: 浮云计算
